version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sns,dynamodb,lambda
      - AWS_DEFAULT_REGION=ap-south-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
    volumes:
      - "./init.sh:/etc/localstack/init/ready.d/init.sh"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recon
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
